spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/paymentdb
    username: pass
    password: 1212
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false # DB ile ish bitdikde session baglanir
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

kafka:
  host: localhost:9092
  topics:
    user-created:
      topic: ms-reservation.booking_created.2
      consumerGroup: ${spring.application.name}-booking-created-consumer
    payment-created:
      topicName: ${spring.application.name}.payment_created.3
      partitionCount: 1
      replicationFactor: 1
      retentionInMs: 604800000  # Kafka retention policy for 7 days

server:
  port: 9097
  servlet:
    session:
      timeout: 30
